version: '3.7'
services:
  acme-explorer-api:
    container_name: acme-explorer-backend-api-container
    hostname: acme-explorer-backend-api-host
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    restart: on-failure
    environment:
      #- NODE_ENV=${NODE_ENV:-development}
      - mongoDBHostname=mongodb
      - mongoDBPort=27017
      - mongoDBUser=${mongoDBUser:-mongoUser}
      - mongoDBPass=${mongoDBPass:-mongoPassword}
      - mongoDBName=${mongoDBName:-acme_explorer}
      - PORT=${PORT:-8080}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_ADMIN_PRIVATE_KEY=${FIREBASE_ADMIN_PRIVATE_KEY}
    depends_on:
      - mongodb
    volumes:
      - ./logging:/usr/src/app/logs
      - ../:/usr/src/app
      - /usr/src/app/node_modules
  mongodb:
    container_name: acme-explorer-backend-mongodb-container
    hostname: acme-explorer-backend-mongodb-host
    image: "mongo"
    restart: unless-stopped
    command: --logpath /var/log/mongodb/db.log
    ports:
      - '${MONGO_DB_PORT:-27017}:27017'
    volumes:
      - ./mongodbdata:/data/db
      - ./logging:/var/log/mongodb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${mongoDBUser:-mongoUser}
      - MONGO_INITDB_ROOT_PASSWORD=${mongoDBPass:-mongoPassword}
      - MONGO_INITDB_DATABASE=${mongoDBName:-acme_explorer}
